-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2016.1
-- Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity sepImageFilter_division is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    vt_pixelOut_V : IN STD_LOGIC_VECTOR (36 downto 0);
    div_V : IN STD_LOGIC_VECTOR (19 downto 0);
    norm_V : IN STD_LOGIC_VECTOR (0 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_ce : IN STD_LOGIC );
end;


architecture behav of sepImageFilter_division is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_true : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";

    signal norm_V_read_read_fu_12_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal norm_V_read_reg_57 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_norm_V_read_reg_57_pp0_iter1 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_norm_V_read_reg_57_pp0_iter2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_norm_V_read_reg_57_pp0_iter3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_norm_V_read_reg_57_pp0_iter4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_norm_V_read_reg_57_pp0_iter5 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_norm_V_read_reg_57_pp0_iter6 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_norm_V_read_reg_57_pp0_iter7 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_norm_V_read_reg_57_pp0_iter8 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_norm_V_read_reg_57_pp0_iter9 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_norm_V_read_reg_57_pp0_iter10 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_norm_V_read_reg_57_pp0_iter11 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_norm_V_read_reg_57_pp0_iter12 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_norm_V_read_reg_57_pp0_iter13 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_norm_V_read_reg_57_pp0_iter14 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_norm_V_read_reg_57_pp0_iter15 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_norm_V_read_reg_57_pp0_iter16 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_norm_V_read_reg_57_pp0_iter17 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_norm_V_read_reg_57_pp0_iter18 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_norm_V_read_reg_57_pp0_iter19 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_norm_V_read_reg_57_pp0_iter20 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_norm_V_read_reg_57_pp0_iter21 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_norm_V_read_reg_57_pp0_iter22 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_norm_V_read_reg_57_pp0_iter23 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_norm_V_read_reg_57_pp0_iter24 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_norm_V_read_reg_57_pp0_iter25 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_norm_V_read_reg_57_pp0_iter26 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_norm_V_read_reg_57_pp0_iter27 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_norm_V_read_reg_57_pp0_iter28 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_norm_V_read_reg_57_pp0_iter29 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_norm_V_read_reg_57_pp0_iter30 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_norm_V_read_reg_57_pp0_iter31 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_norm_V_read_reg_57_pp0_iter32 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_norm_V_read_reg_57_pp0_iter33 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_norm_V_read_reg_57_pp0_iter34 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_norm_V_read_reg_57_pp0_iter35 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_norm_V_read_reg_57_pp0_iter36 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_norm_V_read_reg_57_pp0_iter37 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_norm_V_read_reg_57_pp0_iter38 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_norm_V_read_reg_57_pp0_iter39 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_norm_V_read_reg_57_pp0_iter40 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_norm_V_read_reg_57_pp0_iter41 : STD_LOGIC_VECTOR (0 downto 0);
    signal vt_pixelOut_V_cast_fu_39_p1 : STD_LOGIC_VECTOR (37 downto 0);
    signal grp_fu_47_p2 : STD_LOGIC_VECTOR (37 downto 0);
    signal r_V_reg_72 : STD_LOGIC_VECTOR (37 downto 0);
    signal ap_reg_phiprechg_storemerge_in_reg_30pp0_it42 : STD_LOGIC_VECTOR (37 downto 0);
    signal storemerge_in_phi_fu_33_p4 : STD_LOGIC_VECTOR (37 downto 0);
    signal ap_reg_phiprechg_storemerge_in_reg_30pp0_it0 : STD_LOGIC_VECTOR (37 downto 0);
    signal ap_reg_phiprechg_storemerge_in_reg_30pp0_it1 : STD_LOGIC_VECTOR (37 downto 0);
    signal ap_reg_phiprechg_storemerge_in_reg_30pp0_it2 : STD_LOGIC_VECTOR (37 downto 0);
    signal ap_reg_phiprechg_storemerge_in_reg_30pp0_it3 : STD_LOGIC_VECTOR (37 downto 0);
    signal ap_reg_phiprechg_storemerge_in_reg_30pp0_it4 : STD_LOGIC_VECTOR (37 downto 0);
    signal ap_reg_phiprechg_storemerge_in_reg_30pp0_it5 : STD_LOGIC_VECTOR (37 downto 0);
    signal ap_reg_phiprechg_storemerge_in_reg_30pp0_it6 : STD_LOGIC_VECTOR (37 downto 0);
    signal ap_reg_phiprechg_storemerge_in_reg_30pp0_it7 : STD_LOGIC_VECTOR (37 downto 0);
    signal ap_reg_phiprechg_storemerge_in_reg_30pp0_it8 : STD_LOGIC_VECTOR (37 downto 0);
    signal ap_reg_phiprechg_storemerge_in_reg_30pp0_it9 : STD_LOGIC_VECTOR (37 downto 0);
    signal ap_reg_phiprechg_storemerge_in_reg_30pp0_it10 : STD_LOGIC_VECTOR (37 downto 0);
    signal ap_reg_phiprechg_storemerge_in_reg_30pp0_it11 : STD_LOGIC_VECTOR (37 downto 0);
    signal ap_reg_phiprechg_storemerge_in_reg_30pp0_it12 : STD_LOGIC_VECTOR (37 downto 0);
    signal ap_reg_phiprechg_storemerge_in_reg_30pp0_it13 : STD_LOGIC_VECTOR (37 downto 0);
    signal ap_reg_phiprechg_storemerge_in_reg_30pp0_it14 : STD_LOGIC_VECTOR (37 downto 0);
    signal ap_reg_phiprechg_storemerge_in_reg_30pp0_it15 : STD_LOGIC_VECTOR (37 downto 0);
    signal ap_reg_phiprechg_storemerge_in_reg_30pp0_it16 : STD_LOGIC_VECTOR (37 downto 0);
    signal ap_reg_phiprechg_storemerge_in_reg_30pp0_it17 : STD_LOGIC_VECTOR (37 downto 0);
    signal ap_reg_phiprechg_storemerge_in_reg_30pp0_it18 : STD_LOGIC_VECTOR (37 downto 0);
    signal ap_reg_phiprechg_storemerge_in_reg_30pp0_it19 : STD_LOGIC_VECTOR (37 downto 0);
    signal ap_reg_phiprechg_storemerge_in_reg_30pp0_it20 : STD_LOGIC_VECTOR (37 downto 0);
    signal ap_reg_phiprechg_storemerge_in_reg_30pp0_it21 : STD_LOGIC_VECTOR (37 downto 0);
    signal ap_reg_phiprechg_storemerge_in_reg_30pp0_it22 : STD_LOGIC_VECTOR (37 downto 0);
    signal ap_reg_phiprechg_storemerge_in_reg_30pp0_it23 : STD_LOGIC_VECTOR (37 downto 0);
    signal ap_reg_phiprechg_storemerge_in_reg_30pp0_it24 : STD_LOGIC_VECTOR (37 downto 0);
    signal ap_reg_phiprechg_storemerge_in_reg_30pp0_it25 : STD_LOGIC_VECTOR (37 downto 0);
    signal ap_reg_phiprechg_storemerge_in_reg_30pp0_it26 : STD_LOGIC_VECTOR (37 downto 0);
    signal ap_reg_phiprechg_storemerge_in_reg_30pp0_it27 : STD_LOGIC_VECTOR (37 downto 0);
    signal ap_reg_phiprechg_storemerge_in_reg_30pp0_it28 : STD_LOGIC_VECTOR (37 downto 0);
    signal ap_reg_phiprechg_storemerge_in_reg_30pp0_it29 : STD_LOGIC_VECTOR (37 downto 0);
    signal ap_reg_phiprechg_storemerge_in_reg_30pp0_it30 : STD_LOGIC_VECTOR (37 downto 0);
    signal ap_reg_phiprechg_storemerge_in_reg_30pp0_it31 : STD_LOGIC_VECTOR (37 downto 0);
    signal ap_reg_phiprechg_storemerge_in_reg_30pp0_it32 : STD_LOGIC_VECTOR (37 downto 0);
    signal ap_reg_phiprechg_storemerge_in_reg_30pp0_it33 : STD_LOGIC_VECTOR (37 downto 0);
    signal ap_reg_phiprechg_storemerge_in_reg_30pp0_it34 : STD_LOGIC_VECTOR (37 downto 0);
    signal ap_reg_phiprechg_storemerge_in_reg_30pp0_it35 : STD_LOGIC_VECTOR (37 downto 0);
    signal ap_reg_phiprechg_storemerge_in_reg_30pp0_it36 : STD_LOGIC_VECTOR (37 downto 0);
    signal ap_reg_phiprechg_storemerge_in_reg_30pp0_it37 : STD_LOGIC_VECTOR (37 downto 0);
    signal ap_reg_phiprechg_storemerge_in_reg_30pp0_it38 : STD_LOGIC_VECTOR (37 downto 0);
    signal ap_reg_phiprechg_storemerge_in_reg_30pp0_it39 : STD_LOGIC_VECTOR (37 downto 0);
    signal ap_reg_phiprechg_storemerge_in_reg_30pp0_it40 : STD_LOGIC_VECTOR (37 downto 0);
    signal ap_reg_phiprechg_storemerge_in_reg_30pp0_it41 : STD_LOGIC_VECTOR (37 downto 0);
    signal grp_fu_47_p0 : STD_LOGIC_VECTOR (37 downto 0);
    signal grp_fu_47_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal grp_fu_47_ce : STD_LOGIC;
    signal grp_fu_47_p10 : STD_LOGIC_VECTOR (37 downto 0);

    component sepImageFilter_sdiv_38s_21ns_38_42 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (37 downto 0);
        din1 : IN STD_LOGIC_VECTOR (20 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (37 downto 0) );
    end component;



begin
    sepImageFilter_sdiv_38s_21ns_38_42_U139 : component sepImageFilter_sdiv_38s_21ns_38_42
    generic map (
        ID => 1,
        NUM_STAGE => 42,
        din0_WIDTH => 38,
        din1_WIDTH => 21,
        dout_WIDTH => 38)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_47_p0,
        din1 => grp_fu_47_p1,
        ce => grp_fu_47_ce,
        dout => grp_fu_47_p2);





    ap_reg_phiprechg_storemerge_in_reg_30pp0_it1_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce)) then
                if ((norm_V_read_read_fu_12_p2 = ap_const_lv1_0)) then 
                    ap_reg_phiprechg_storemerge_in_reg_30pp0_it1 <= vt_pixelOut_V_cast_fu_39_p1;
                elsif ((ap_true = ap_true)) then 
                    ap_reg_phiprechg_storemerge_in_reg_30pp0_it1 <= ap_reg_phiprechg_storemerge_in_reg_30pp0_it0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce)) then
                ap_reg_phiprechg_storemerge_in_reg_30pp0_it10 <= ap_reg_phiprechg_storemerge_in_reg_30pp0_it9;
                ap_reg_phiprechg_storemerge_in_reg_30pp0_it11 <= ap_reg_phiprechg_storemerge_in_reg_30pp0_it10;
                ap_reg_phiprechg_storemerge_in_reg_30pp0_it12 <= ap_reg_phiprechg_storemerge_in_reg_30pp0_it11;
                ap_reg_phiprechg_storemerge_in_reg_30pp0_it13 <= ap_reg_phiprechg_storemerge_in_reg_30pp0_it12;
                ap_reg_phiprechg_storemerge_in_reg_30pp0_it14 <= ap_reg_phiprechg_storemerge_in_reg_30pp0_it13;
                ap_reg_phiprechg_storemerge_in_reg_30pp0_it15 <= ap_reg_phiprechg_storemerge_in_reg_30pp0_it14;
                ap_reg_phiprechg_storemerge_in_reg_30pp0_it16 <= ap_reg_phiprechg_storemerge_in_reg_30pp0_it15;
                ap_reg_phiprechg_storemerge_in_reg_30pp0_it17 <= ap_reg_phiprechg_storemerge_in_reg_30pp0_it16;
                ap_reg_phiprechg_storemerge_in_reg_30pp0_it18 <= ap_reg_phiprechg_storemerge_in_reg_30pp0_it17;
                ap_reg_phiprechg_storemerge_in_reg_30pp0_it19 <= ap_reg_phiprechg_storemerge_in_reg_30pp0_it18;
                ap_reg_phiprechg_storemerge_in_reg_30pp0_it2 <= ap_reg_phiprechg_storemerge_in_reg_30pp0_it1;
                ap_reg_phiprechg_storemerge_in_reg_30pp0_it20 <= ap_reg_phiprechg_storemerge_in_reg_30pp0_it19;
                ap_reg_phiprechg_storemerge_in_reg_30pp0_it21 <= ap_reg_phiprechg_storemerge_in_reg_30pp0_it20;
                ap_reg_phiprechg_storemerge_in_reg_30pp0_it22 <= ap_reg_phiprechg_storemerge_in_reg_30pp0_it21;
                ap_reg_phiprechg_storemerge_in_reg_30pp0_it23 <= ap_reg_phiprechg_storemerge_in_reg_30pp0_it22;
                ap_reg_phiprechg_storemerge_in_reg_30pp0_it24 <= ap_reg_phiprechg_storemerge_in_reg_30pp0_it23;
                ap_reg_phiprechg_storemerge_in_reg_30pp0_it25 <= ap_reg_phiprechg_storemerge_in_reg_30pp0_it24;
                ap_reg_phiprechg_storemerge_in_reg_30pp0_it26 <= ap_reg_phiprechg_storemerge_in_reg_30pp0_it25;
                ap_reg_phiprechg_storemerge_in_reg_30pp0_it27 <= ap_reg_phiprechg_storemerge_in_reg_30pp0_it26;
                ap_reg_phiprechg_storemerge_in_reg_30pp0_it28 <= ap_reg_phiprechg_storemerge_in_reg_30pp0_it27;
                ap_reg_phiprechg_storemerge_in_reg_30pp0_it29 <= ap_reg_phiprechg_storemerge_in_reg_30pp0_it28;
                ap_reg_phiprechg_storemerge_in_reg_30pp0_it3 <= ap_reg_phiprechg_storemerge_in_reg_30pp0_it2;
                ap_reg_phiprechg_storemerge_in_reg_30pp0_it30 <= ap_reg_phiprechg_storemerge_in_reg_30pp0_it29;
                ap_reg_phiprechg_storemerge_in_reg_30pp0_it31 <= ap_reg_phiprechg_storemerge_in_reg_30pp0_it30;
                ap_reg_phiprechg_storemerge_in_reg_30pp0_it32 <= ap_reg_phiprechg_storemerge_in_reg_30pp0_it31;
                ap_reg_phiprechg_storemerge_in_reg_30pp0_it33 <= ap_reg_phiprechg_storemerge_in_reg_30pp0_it32;
                ap_reg_phiprechg_storemerge_in_reg_30pp0_it34 <= ap_reg_phiprechg_storemerge_in_reg_30pp0_it33;
                ap_reg_phiprechg_storemerge_in_reg_30pp0_it35 <= ap_reg_phiprechg_storemerge_in_reg_30pp0_it34;
                ap_reg_phiprechg_storemerge_in_reg_30pp0_it36 <= ap_reg_phiprechg_storemerge_in_reg_30pp0_it35;
                ap_reg_phiprechg_storemerge_in_reg_30pp0_it37 <= ap_reg_phiprechg_storemerge_in_reg_30pp0_it36;
                ap_reg_phiprechg_storemerge_in_reg_30pp0_it38 <= ap_reg_phiprechg_storemerge_in_reg_30pp0_it37;
                ap_reg_phiprechg_storemerge_in_reg_30pp0_it39 <= ap_reg_phiprechg_storemerge_in_reg_30pp0_it38;
                ap_reg_phiprechg_storemerge_in_reg_30pp0_it4 <= ap_reg_phiprechg_storemerge_in_reg_30pp0_it3;
                ap_reg_phiprechg_storemerge_in_reg_30pp0_it40 <= ap_reg_phiprechg_storemerge_in_reg_30pp0_it39;
                ap_reg_phiprechg_storemerge_in_reg_30pp0_it41 <= ap_reg_phiprechg_storemerge_in_reg_30pp0_it40;
                ap_reg_phiprechg_storemerge_in_reg_30pp0_it42 <= ap_reg_phiprechg_storemerge_in_reg_30pp0_it41;
                ap_reg_phiprechg_storemerge_in_reg_30pp0_it5 <= ap_reg_phiprechg_storemerge_in_reg_30pp0_it4;
                ap_reg_phiprechg_storemerge_in_reg_30pp0_it6 <= ap_reg_phiprechg_storemerge_in_reg_30pp0_it5;
                ap_reg_phiprechg_storemerge_in_reg_30pp0_it7 <= ap_reg_phiprechg_storemerge_in_reg_30pp0_it6;
                ap_reg_phiprechg_storemerge_in_reg_30pp0_it8 <= ap_reg_phiprechg_storemerge_in_reg_30pp0_it7;
                ap_reg_phiprechg_storemerge_in_reg_30pp0_it9 <= ap_reg_phiprechg_storemerge_in_reg_30pp0_it8;
                ap_reg_ppstg_norm_V_read_reg_57_pp0_iter1 <= norm_V_read_reg_57;
                ap_reg_ppstg_norm_V_read_reg_57_pp0_iter10 <= ap_reg_ppstg_norm_V_read_reg_57_pp0_iter9;
                ap_reg_ppstg_norm_V_read_reg_57_pp0_iter11 <= ap_reg_ppstg_norm_V_read_reg_57_pp0_iter10;
                ap_reg_ppstg_norm_V_read_reg_57_pp0_iter12 <= ap_reg_ppstg_norm_V_read_reg_57_pp0_iter11;
                ap_reg_ppstg_norm_V_read_reg_57_pp0_iter13 <= ap_reg_ppstg_norm_V_read_reg_57_pp0_iter12;
                ap_reg_ppstg_norm_V_read_reg_57_pp0_iter14 <= ap_reg_ppstg_norm_V_read_reg_57_pp0_iter13;
                ap_reg_ppstg_norm_V_read_reg_57_pp0_iter15 <= ap_reg_ppstg_norm_V_read_reg_57_pp0_iter14;
                ap_reg_ppstg_norm_V_read_reg_57_pp0_iter16 <= ap_reg_ppstg_norm_V_read_reg_57_pp0_iter15;
                ap_reg_ppstg_norm_V_read_reg_57_pp0_iter17 <= ap_reg_ppstg_norm_V_read_reg_57_pp0_iter16;
                ap_reg_ppstg_norm_V_read_reg_57_pp0_iter18 <= ap_reg_ppstg_norm_V_read_reg_57_pp0_iter17;
                ap_reg_ppstg_norm_V_read_reg_57_pp0_iter19 <= ap_reg_ppstg_norm_V_read_reg_57_pp0_iter18;
                ap_reg_ppstg_norm_V_read_reg_57_pp0_iter2 <= ap_reg_ppstg_norm_V_read_reg_57_pp0_iter1;
                ap_reg_ppstg_norm_V_read_reg_57_pp0_iter20 <= ap_reg_ppstg_norm_V_read_reg_57_pp0_iter19;
                ap_reg_ppstg_norm_V_read_reg_57_pp0_iter21 <= ap_reg_ppstg_norm_V_read_reg_57_pp0_iter20;
                ap_reg_ppstg_norm_V_read_reg_57_pp0_iter22 <= ap_reg_ppstg_norm_V_read_reg_57_pp0_iter21;
                ap_reg_ppstg_norm_V_read_reg_57_pp0_iter23 <= ap_reg_ppstg_norm_V_read_reg_57_pp0_iter22;
                ap_reg_ppstg_norm_V_read_reg_57_pp0_iter24 <= ap_reg_ppstg_norm_V_read_reg_57_pp0_iter23;
                ap_reg_ppstg_norm_V_read_reg_57_pp0_iter25 <= ap_reg_ppstg_norm_V_read_reg_57_pp0_iter24;
                ap_reg_ppstg_norm_V_read_reg_57_pp0_iter26 <= ap_reg_ppstg_norm_V_read_reg_57_pp0_iter25;
                ap_reg_ppstg_norm_V_read_reg_57_pp0_iter27 <= ap_reg_ppstg_norm_V_read_reg_57_pp0_iter26;
                ap_reg_ppstg_norm_V_read_reg_57_pp0_iter28 <= ap_reg_ppstg_norm_V_read_reg_57_pp0_iter27;
                ap_reg_ppstg_norm_V_read_reg_57_pp0_iter29 <= ap_reg_ppstg_norm_V_read_reg_57_pp0_iter28;
                ap_reg_ppstg_norm_V_read_reg_57_pp0_iter3 <= ap_reg_ppstg_norm_V_read_reg_57_pp0_iter2;
                ap_reg_ppstg_norm_V_read_reg_57_pp0_iter30 <= ap_reg_ppstg_norm_V_read_reg_57_pp0_iter29;
                ap_reg_ppstg_norm_V_read_reg_57_pp0_iter31 <= ap_reg_ppstg_norm_V_read_reg_57_pp0_iter30;
                ap_reg_ppstg_norm_V_read_reg_57_pp0_iter32 <= ap_reg_ppstg_norm_V_read_reg_57_pp0_iter31;
                ap_reg_ppstg_norm_V_read_reg_57_pp0_iter33 <= ap_reg_ppstg_norm_V_read_reg_57_pp0_iter32;
                ap_reg_ppstg_norm_V_read_reg_57_pp0_iter34 <= ap_reg_ppstg_norm_V_read_reg_57_pp0_iter33;
                ap_reg_ppstg_norm_V_read_reg_57_pp0_iter35 <= ap_reg_ppstg_norm_V_read_reg_57_pp0_iter34;
                ap_reg_ppstg_norm_V_read_reg_57_pp0_iter36 <= ap_reg_ppstg_norm_V_read_reg_57_pp0_iter35;
                ap_reg_ppstg_norm_V_read_reg_57_pp0_iter37 <= ap_reg_ppstg_norm_V_read_reg_57_pp0_iter36;
                ap_reg_ppstg_norm_V_read_reg_57_pp0_iter38 <= ap_reg_ppstg_norm_V_read_reg_57_pp0_iter37;
                ap_reg_ppstg_norm_V_read_reg_57_pp0_iter39 <= ap_reg_ppstg_norm_V_read_reg_57_pp0_iter38;
                ap_reg_ppstg_norm_V_read_reg_57_pp0_iter4 <= ap_reg_ppstg_norm_V_read_reg_57_pp0_iter3;
                ap_reg_ppstg_norm_V_read_reg_57_pp0_iter40 <= ap_reg_ppstg_norm_V_read_reg_57_pp0_iter39;
                ap_reg_ppstg_norm_V_read_reg_57_pp0_iter41 <= ap_reg_ppstg_norm_V_read_reg_57_pp0_iter40;
                ap_reg_ppstg_norm_V_read_reg_57_pp0_iter5 <= ap_reg_ppstg_norm_V_read_reg_57_pp0_iter4;
                ap_reg_ppstg_norm_V_read_reg_57_pp0_iter6 <= ap_reg_ppstg_norm_V_read_reg_57_pp0_iter5;
                ap_reg_ppstg_norm_V_read_reg_57_pp0_iter7 <= ap_reg_ppstg_norm_V_read_reg_57_pp0_iter6;
                ap_reg_ppstg_norm_V_read_reg_57_pp0_iter8 <= ap_reg_ppstg_norm_V_read_reg_57_pp0_iter7;
                ap_reg_ppstg_norm_V_read_reg_57_pp0_iter9 <= ap_reg_ppstg_norm_V_read_reg_57_pp0_iter8;
                norm_V_read_reg_57 <= norm_V;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_ce) and not((ap_reg_ppstg_norm_V_read_reg_57_pp0_iter40 = ap_const_lv1_0)))) then
                r_V_reg_72 <= grp_fu_47_p2;
            end if;
        end if;
    end process;
    ap_reg_phiprechg_storemerge_in_reg_30pp0_it0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_return <= storemerge_in_phi_fu_33_p4(16 - 1 downto 0);

    grp_fu_47_ce_assign_proc : process(ap_ce)
    begin
        if ((ap_const_logic_1 = ap_ce)) then 
            grp_fu_47_ce <= ap_const_logic_1;
        else 
            grp_fu_47_ce <= ap_const_logic_0;
        end if; 
    end process;

        grp_fu_47_p0 <= std_logic_vector(resize(signed(vt_pixelOut_V),38));

    grp_fu_47_p1 <= grp_fu_47_p10(21 - 1 downto 0);
    grp_fu_47_p10 <= std_logic_vector(resize(unsigned(div_V),38));
    norm_V_read_read_fu_12_p2 <= norm_V;

    storemerge_in_phi_fu_33_p4_assign_proc : process(ap_reg_ppstg_norm_V_read_reg_57_pp0_iter41, r_V_reg_72, ap_reg_phiprechg_storemerge_in_reg_30pp0_it42)
    begin
        if (not((ap_reg_ppstg_norm_V_read_reg_57_pp0_iter41 = ap_const_lv1_0))) then 
            storemerge_in_phi_fu_33_p4 <= r_V_reg_72;
        else 
            storemerge_in_phi_fu_33_p4 <= ap_reg_phiprechg_storemerge_in_reg_30pp0_it42;
        end if; 
    end process;

        vt_pixelOut_V_cast_fu_39_p1 <= std_logic_vector(resize(signed(vt_pixelOut_V),38));

end behav;
