#ifndef GLOBAL_PARAMETERS_H_
#define GLOBAL_PARAMETERS_H_

#define AXI_DMA_BASEADDR     0x40400000
#define AXI_DMA_HIGHADDR     0x4040FFFF


#define AXI_VDMA_BASEADDR     0x44000000
#define AXI_VDMA_HIGHADDR     0x4400FFFF

#define AXI_GPIO_BASEADDR     0x44000000
#define AXI_GPIO_HIGHADDR     0x4400FFFF

/* Memory buffer starting address (RAM) */
#define BUFFER_MEM_READ_START_ADDRESS        0x1F000000
#define BUFFER_MEM_WRITE_START_ADDRESS       0x1F300000
/* Buffer size = 1M */
#define BUFFER_SIZE				                   0x00100000


#define MEM2VDMA_BUFFER1_BASEADDR		(BUFFER_MEM_WRITE_START_ADDRESS)
#define MEM2VDMA_BUFFER2_BASEADDR		(MEM2VDMA_BUFFER1_BASEADDR + BUFFER_SIZE)
#define MEM2VDMA_BUFFER3_BASEADDR		(MEM2VDMA_BUFFER2_BASEADDR + BUFFER_SIZE)

//#define MEM2VDMA_BUFFER1_BASEADDR		(BUFFER_MEM_READ_START_ADDRESS)
//#define MEM2VDMA_BUFFER2_BASEADDR		(MEM2VDMA_BUFFER1_BASEADDR + BUFFER_SIZE)
//#define MEM2VDMA_BUFFER3_BASEADDR		(MEM2VDMA_BUFFER2_BASEADDR + BUFFER_SIZE)

#define VDMA2MEM_BUFFER1_BASEADDR		(BUFFER_MEM_WRITE_START_ADDRESS)
#define VDMA2MEM_BUFFER2_BASEADDR		(VDMA2MEM_BUFFER1_BASEADDR + BUFFER_SIZE)
#define VDMA2MEM_BUFFER3_BASEADDR		(VDMA2MEM_BUFFER2_BASEADDR + BUFFER_SIZE)



/* Parameter definitions for image capture */
#define IN_FRAME_WIDTH		512		// for use with the test image
#define IN_FRAME_HEIGHT		512		// for use with the test image
//#define IN_FRAME_WIDTH		640		// for use with the camera
//#define IN_FRAME_HEIGHT		480		// for use with the camera
#define PIXEL_CHANNELS      3




#endif
// endif GLOBAL_PARAMETERS_H_
