// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.1
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// CONTROL_BUS
// 0x000 : Control signals
//         bit 0  - ap_start (Read/Write/COH)
//         bit 1  - ap_done (Read/COR)
//         bit 2  - ap_idle (Read)
//         bit 3  - ap_ready (Read)
//         bit 7  - auto_restart (Read/Write)
//         others - reserved
// 0x004 : Global Interrupt Enable Register
//         bit 0  - Global Interrupt Enable (Read/Write)
//         others - reserved
// 0x008 : IP Interrupt Enable Register (Read/Write)
//         bit 0  - Channel 0 (ap_done)
//         bit 1  - Channel 1 (ap_ready)
//         others - reserved
// 0x00c : IP Interrupt Status Register (Read/TOW)
//         bit 0  - Channel 0 (ap_done)
//         bit 1  - Channel 1 (ap_ready)
//         others - reserved
// 0x010 : Data signal of IMG_WIDTH_V
//         bit 10~0 - IMG_WIDTH_V[10:0] (Read/Write)
//         others   - reserved
// 0x014 : reserved
// 0x018 : Data signal of IMG_HEIGHT_V
//         bit 10~0 - IMG_HEIGHT_V[10:0] (Read/Write)
//         others   - reserved
// 0x01c : reserved
// 0x020 : Data signal of hz_kernels_0_0_V
//         bit 7~0 - hz_kernels_0_0_V[7:0] (Read/Write)
//         others  - reserved
// 0x024 : reserved
// 0x028 : Data signal of hz_kernels_0_1_V
//         bit 7~0 - hz_kernels_0_1_V[7:0] (Read/Write)
//         others  - reserved
// 0x02c : reserved
// 0x030 : Data signal of hz_kernels_0_2_V
//         bit 7~0 - hz_kernels_0_2_V[7:0] (Read/Write)
//         others  - reserved
// 0x034 : reserved
// 0x038 : Data signal of hz_kernels_0_3_V
//         bit 7~0 - hz_kernels_0_3_V[7:0] (Read/Write)
//         others  - reserved
// 0x03c : reserved
// 0x040 : Data signal of hz_kernels_0_4_V
//         bit 7~0 - hz_kernels_0_4_V[7:0] (Read/Write)
//         others  - reserved
// 0x044 : reserved
// 0x048 : Data signal of hz_kernels_0_5_V
//         bit 7~0 - hz_kernels_0_5_V[7:0] (Read/Write)
//         others  - reserved
// 0x04c : reserved
// 0x050 : Data signal of hz_kernels_0_6_V
//         bit 7~0 - hz_kernels_0_6_V[7:0] (Read/Write)
//         others  - reserved
// 0x054 : reserved
// 0x058 : Data signal of hz_kernels_1_0_V
//         bit 7~0 - hz_kernels_1_0_V[7:0] (Read/Write)
//         others  - reserved
// 0x05c : reserved
// 0x060 : Data signal of hz_kernels_1_1_V
//         bit 7~0 - hz_kernels_1_1_V[7:0] (Read/Write)
//         others  - reserved
// 0x064 : reserved
// 0x068 : Data signal of hz_kernels_1_2_V
//         bit 7~0 - hz_kernels_1_2_V[7:0] (Read/Write)
//         others  - reserved
// 0x06c : reserved
// 0x070 : Data signal of hz_kernels_1_3_V
//         bit 7~0 - hz_kernels_1_3_V[7:0] (Read/Write)
//         others  - reserved
// 0x074 : reserved
// 0x078 : Data signal of hz_kernels_1_4_V
//         bit 7~0 - hz_kernels_1_4_V[7:0] (Read/Write)
//         others  - reserved
// 0x07c : reserved
// 0x080 : Data signal of hz_kernels_1_5_V
//         bit 7~0 - hz_kernels_1_5_V[7:0] (Read/Write)
//         others  - reserved
// 0x084 : reserved
// 0x088 : Data signal of hz_kernels_1_6_V
//         bit 7~0 - hz_kernels_1_6_V[7:0] (Read/Write)
//         others  - reserved
// 0x08c : reserved
// 0x090 : Data signal of hz_kernels_2_0_V
//         bit 7~0 - hz_kernels_2_0_V[7:0] (Read/Write)
//         others  - reserved
// 0x094 : reserved
// 0x098 : Data signal of hz_kernels_2_1_V
//         bit 7~0 - hz_kernels_2_1_V[7:0] (Read/Write)
//         others  - reserved
// 0x09c : reserved
// 0x0a0 : Data signal of hz_kernels_2_2_V
//         bit 7~0 - hz_kernels_2_2_V[7:0] (Read/Write)
//         others  - reserved
// 0x0a4 : reserved
// 0x0a8 : Data signal of hz_kernels_2_3_V
//         bit 7~0 - hz_kernels_2_3_V[7:0] (Read/Write)
//         others  - reserved
// 0x0ac : reserved
// 0x0b0 : Data signal of hz_kernels_2_4_V
//         bit 7~0 - hz_kernels_2_4_V[7:0] (Read/Write)
//         others  - reserved
// 0x0b4 : reserved
// 0x0b8 : Data signal of hz_kernels_2_5_V
//         bit 7~0 - hz_kernels_2_5_V[7:0] (Read/Write)
//         others  - reserved
// 0x0bc : reserved
// 0x0c0 : Data signal of hz_kernels_2_6_V
//         bit 7~0 - hz_kernels_2_6_V[7:0] (Read/Write)
//         others  - reserved
// 0x0c4 : reserved
// 0x0c8 : Data signal of vt_kernels_0_0_V
//         bit 7~0 - vt_kernels_0_0_V[7:0] (Read/Write)
//         others  - reserved
// 0x0cc : reserved
// 0x0d0 : Data signal of vt_kernels_0_1_V
//         bit 7~0 - vt_kernels_0_1_V[7:0] (Read/Write)
//         others  - reserved
// 0x0d4 : reserved
// 0x0d8 : Data signal of vt_kernels_0_2_V
//         bit 7~0 - vt_kernels_0_2_V[7:0] (Read/Write)
//         others  - reserved
// 0x0dc : reserved
// 0x0e0 : Data signal of vt_kernels_0_3_V
//         bit 7~0 - vt_kernels_0_3_V[7:0] (Read/Write)
//         others  - reserved
// 0x0e4 : reserved
// 0x0e8 : Data signal of vt_kernels_0_4_V
//         bit 7~0 - vt_kernels_0_4_V[7:0] (Read/Write)
//         others  - reserved
// 0x0ec : reserved
// 0x0f0 : Data signal of vt_kernels_0_5_V
//         bit 7~0 - vt_kernels_0_5_V[7:0] (Read/Write)
//         others  - reserved
// 0x0f4 : reserved
// 0x0f8 : Data signal of vt_kernels_0_6_V
//         bit 7~0 - vt_kernels_0_6_V[7:0] (Read/Write)
//         others  - reserved
// 0x0fc : reserved
// 0x100 : Data signal of vt_kernels_1_0_V
//         bit 7~0 - vt_kernels_1_0_V[7:0] (Read/Write)
//         others  - reserved
// 0x104 : reserved
// 0x108 : Data signal of vt_kernels_1_1_V
//         bit 7~0 - vt_kernels_1_1_V[7:0] (Read/Write)
//         others  - reserved
// 0x10c : reserved
// 0x110 : Data signal of vt_kernels_1_2_V
//         bit 7~0 - vt_kernels_1_2_V[7:0] (Read/Write)
//         others  - reserved
// 0x114 : reserved
// 0x118 : Data signal of vt_kernels_1_3_V
//         bit 7~0 - vt_kernels_1_3_V[7:0] (Read/Write)
//         others  - reserved
// 0x11c : reserved
// 0x120 : Data signal of vt_kernels_1_4_V
//         bit 7~0 - vt_kernels_1_4_V[7:0] (Read/Write)
//         others  - reserved
// 0x124 : reserved
// 0x128 : Data signal of vt_kernels_1_5_V
//         bit 7~0 - vt_kernels_1_5_V[7:0] (Read/Write)
//         others  - reserved
// 0x12c : reserved
// 0x130 : Data signal of vt_kernels_1_6_V
//         bit 7~0 - vt_kernels_1_6_V[7:0] (Read/Write)
//         others  - reserved
// 0x134 : reserved
// 0x138 : Data signal of vt_kernels_2_0_V
//         bit 7~0 - vt_kernels_2_0_V[7:0] (Read/Write)
//         others  - reserved
// 0x13c : reserved
// 0x140 : Data signal of vt_kernels_2_1_V
//         bit 7~0 - vt_kernels_2_1_V[7:0] (Read/Write)
//         others  - reserved
// 0x144 : reserved
// 0x148 : Data signal of vt_kernels_2_2_V
//         bit 7~0 - vt_kernels_2_2_V[7:0] (Read/Write)
//         others  - reserved
// 0x14c : reserved
// 0x150 : Data signal of vt_kernels_2_3_V
//         bit 7~0 - vt_kernels_2_3_V[7:0] (Read/Write)
//         others  - reserved
// 0x154 : reserved
// 0x158 : Data signal of vt_kernels_2_4_V
//         bit 7~0 - vt_kernels_2_4_V[7:0] (Read/Write)
//         others  - reserved
// 0x15c : reserved
// 0x160 : Data signal of vt_kernels_2_5_V
//         bit 7~0 - vt_kernels_2_5_V[7:0] (Read/Write)
//         others  - reserved
// 0x164 : reserved
// 0x168 : Data signal of vt_kernels_2_6_V
//         bit 7~0 - vt_kernels_2_6_V[7:0] (Read/Write)
//         others  - reserved
// 0x16c : reserved
// 0x170 : Data signal of config_V
//         bit 7~0 - config_V[7:0] (Read/Write)
//         others  - reserved
// 0x174 : reserved
// 0x178 : Data signal of divisor_0_V
//         bit 19~0 - divisor_0_V[19:0] (Read/Write)
//         others   - reserved
// 0x17c : reserved
// 0x180 : Data signal of divisor_1_V
//         bit 19~0 - divisor_1_V[19:0] (Read/Write)
//         others   - reserved
// 0x184 : reserved
// 0x188 : Data signal of divisor_2_V
//         bit 19~0 - divisor_2_V[19:0] (Read/Write)
//         others   - reserved
// 0x18c : reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XSEPIMAGEFILTER_CONTROL_BUS_ADDR_AP_CTRL               0x000
#define XSEPIMAGEFILTER_CONTROL_BUS_ADDR_GIE                   0x004
#define XSEPIMAGEFILTER_CONTROL_BUS_ADDR_IER                   0x008
#define XSEPIMAGEFILTER_CONTROL_BUS_ADDR_ISR                   0x00c
#define XSEPIMAGEFILTER_CONTROL_BUS_ADDR_IMG_WIDTH_V_DATA      0x010
#define XSEPIMAGEFILTER_CONTROL_BUS_BITS_IMG_WIDTH_V_DATA      11
#define XSEPIMAGEFILTER_CONTROL_BUS_ADDR_IMG_HEIGHT_V_DATA     0x018
#define XSEPIMAGEFILTER_CONTROL_BUS_BITS_IMG_HEIGHT_V_DATA     11
#define XSEPIMAGEFILTER_CONTROL_BUS_ADDR_HZ_KERNELS_0_0_V_DATA 0x020
#define XSEPIMAGEFILTER_CONTROL_BUS_BITS_HZ_KERNELS_0_0_V_DATA 8
#define XSEPIMAGEFILTER_CONTROL_BUS_ADDR_HZ_KERNELS_0_1_V_DATA 0x028
#define XSEPIMAGEFILTER_CONTROL_BUS_BITS_HZ_KERNELS_0_1_V_DATA 8
#define XSEPIMAGEFILTER_CONTROL_BUS_ADDR_HZ_KERNELS_0_2_V_DATA 0x030
#define XSEPIMAGEFILTER_CONTROL_BUS_BITS_HZ_KERNELS_0_2_V_DATA 8
#define XSEPIMAGEFILTER_CONTROL_BUS_ADDR_HZ_KERNELS_0_3_V_DATA 0x038
#define XSEPIMAGEFILTER_CONTROL_BUS_BITS_HZ_KERNELS_0_3_V_DATA 8
#define XSEPIMAGEFILTER_CONTROL_BUS_ADDR_HZ_KERNELS_0_4_V_DATA 0x040
#define XSEPIMAGEFILTER_CONTROL_BUS_BITS_HZ_KERNELS_0_4_V_DATA 8
#define XSEPIMAGEFILTER_CONTROL_BUS_ADDR_HZ_KERNELS_0_5_V_DATA 0x048
#define XSEPIMAGEFILTER_CONTROL_BUS_BITS_HZ_KERNELS_0_5_V_DATA 8
#define XSEPIMAGEFILTER_CONTROL_BUS_ADDR_HZ_KERNELS_0_6_V_DATA 0x050
#define XSEPIMAGEFILTER_CONTROL_BUS_BITS_HZ_KERNELS_0_6_V_DATA 8
#define XSEPIMAGEFILTER_CONTROL_BUS_ADDR_HZ_KERNELS_1_0_V_DATA 0x058
#define XSEPIMAGEFILTER_CONTROL_BUS_BITS_HZ_KERNELS_1_0_V_DATA 8
#define XSEPIMAGEFILTER_CONTROL_BUS_ADDR_HZ_KERNELS_1_1_V_DATA 0x060
#define XSEPIMAGEFILTER_CONTROL_BUS_BITS_HZ_KERNELS_1_1_V_DATA 8
#define XSEPIMAGEFILTER_CONTROL_BUS_ADDR_HZ_KERNELS_1_2_V_DATA 0x068
#define XSEPIMAGEFILTER_CONTROL_BUS_BITS_HZ_KERNELS_1_2_V_DATA 8
#define XSEPIMAGEFILTER_CONTROL_BUS_ADDR_HZ_KERNELS_1_3_V_DATA 0x070
#define XSEPIMAGEFILTER_CONTROL_BUS_BITS_HZ_KERNELS_1_3_V_DATA 8
#define XSEPIMAGEFILTER_CONTROL_BUS_ADDR_HZ_KERNELS_1_4_V_DATA 0x078
#define XSEPIMAGEFILTER_CONTROL_BUS_BITS_HZ_KERNELS_1_4_V_DATA 8
#define XSEPIMAGEFILTER_CONTROL_BUS_ADDR_HZ_KERNELS_1_5_V_DATA 0x080
#define XSEPIMAGEFILTER_CONTROL_BUS_BITS_HZ_KERNELS_1_5_V_DATA 8
#define XSEPIMAGEFILTER_CONTROL_BUS_ADDR_HZ_KERNELS_1_6_V_DATA 0x088
#define XSEPIMAGEFILTER_CONTROL_BUS_BITS_HZ_KERNELS_1_6_V_DATA 8
#define XSEPIMAGEFILTER_CONTROL_BUS_ADDR_HZ_KERNELS_2_0_V_DATA 0x090
#define XSEPIMAGEFILTER_CONTROL_BUS_BITS_HZ_KERNELS_2_0_V_DATA 8
#define XSEPIMAGEFILTER_CONTROL_BUS_ADDR_HZ_KERNELS_2_1_V_DATA 0x098
#define XSEPIMAGEFILTER_CONTROL_BUS_BITS_HZ_KERNELS_2_1_V_DATA 8
#define XSEPIMAGEFILTER_CONTROL_BUS_ADDR_HZ_KERNELS_2_2_V_DATA 0x0a0
#define XSEPIMAGEFILTER_CONTROL_BUS_BITS_HZ_KERNELS_2_2_V_DATA 8
#define XSEPIMAGEFILTER_CONTROL_BUS_ADDR_HZ_KERNELS_2_3_V_DATA 0x0a8
#define XSEPIMAGEFILTER_CONTROL_BUS_BITS_HZ_KERNELS_2_3_V_DATA 8
#define XSEPIMAGEFILTER_CONTROL_BUS_ADDR_HZ_KERNELS_2_4_V_DATA 0x0b0
#define XSEPIMAGEFILTER_CONTROL_BUS_BITS_HZ_KERNELS_2_4_V_DATA 8
#define XSEPIMAGEFILTER_CONTROL_BUS_ADDR_HZ_KERNELS_2_5_V_DATA 0x0b8
#define XSEPIMAGEFILTER_CONTROL_BUS_BITS_HZ_KERNELS_2_5_V_DATA 8
#define XSEPIMAGEFILTER_CONTROL_BUS_ADDR_HZ_KERNELS_2_6_V_DATA 0x0c0
#define XSEPIMAGEFILTER_CONTROL_BUS_BITS_HZ_KERNELS_2_6_V_DATA 8
#define XSEPIMAGEFILTER_CONTROL_BUS_ADDR_VT_KERNELS_0_0_V_DATA 0x0c8
#define XSEPIMAGEFILTER_CONTROL_BUS_BITS_VT_KERNELS_0_0_V_DATA 8
#define XSEPIMAGEFILTER_CONTROL_BUS_ADDR_VT_KERNELS_0_1_V_DATA 0x0d0
#define XSEPIMAGEFILTER_CONTROL_BUS_BITS_VT_KERNELS_0_1_V_DATA 8
#define XSEPIMAGEFILTER_CONTROL_BUS_ADDR_VT_KERNELS_0_2_V_DATA 0x0d8
#define XSEPIMAGEFILTER_CONTROL_BUS_BITS_VT_KERNELS_0_2_V_DATA 8
#define XSEPIMAGEFILTER_CONTROL_BUS_ADDR_VT_KERNELS_0_3_V_DATA 0x0e0
#define XSEPIMAGEFILTER_CONTROL_BUS_BITS_VT_KERNELS_0_3_V_DATA 8
#define XSEPIMAGEFILTER_CONTROL_BUS_ADDR_VT_KERNELS_0_4_V_DATA 0x0e8
#define XSEPIMAGEFILTER_CONTROL_BUS_BITS_VT_KERNELS_0_4_V_DATA 8
#define XSEPIMAGEFILTER_CONTROL_BUS_ADDR_VT_KERNELS_0_5_V_DATA 0x0f0
#define XSEPIMAGEFILTER_CONTROL_BUS_BITS_VT_KERNELS_0_5_V_DATA 8
#define XSEPIMAGEFILTER_CONTROL_BUS_ADDR_VT_KERNELS_0_6_V_DATA 0x0f8
#define XSEPIMAGEFILTER_CONTROL_BUS_BITS_VT_KERNELS_0_6_V_DATA 8
#define XSEPIMAGEFILTER_CONTROL_BUS_ADDR_VT_KERNELS_1_0_V_DATA 0x100
#define XSEPIMAGEFILTER_CONTROL_BUS_BITS_VT_KERNELS_1_0_V_DATA 8
#define XSEPIMAGEFILTER_CONTROL_BUS_ADDR_VT_KERNELS_1_1_V_DATA 0x108
#define XSEPIMAGEFILTER_CONTROL_BUS_BITS_VT_KERNELS_1_1_V_DATA 8
#define XSEPIMAGEFILTER_CONTROL_BUS_ADDR_VT_KERNELS_1_2_V_DATA 0x110
#define XSEPIMAGEFILTER_CONTROL_BUS_BITS_VT_KERNELS_1_2_V_DATA 8
#define XSEPIMAGEFILTER_CONTROL_BUS_ADDR_VT_KERNELS_1_3_V_DATA 0x118
#define XSEPIMAGEFILTER_CONTROL_BUS_BITS_VT_KERNELS_1_3_V_DATA 8
#define XSEPIMAGEFILTER_CONTROL_BUS_ADDR_VT_KERNELS_1_4_V_DATA 0x120
#define XSEPIMAGEFILTER_CONTROL_BUS_BITS_VT_KERNELS_1_4_V_DATA 8
#define XSEPIMAGEFILTER_CONTROL_BUS_ADDR_VT_KERNELS_1_5_V_DATA 0x128
#define XSEPIMAGEFILTER_CONTROL_BUS_BITS_VT_KERNELS_1_5_V_DATA 8
#define XSEPIMAGEFILTER_CONTROL_BUS_ADDR_VT_KERNELS_1_6_V_DATA 0x130
#define XSEPIMAGEFILTER_CONTROL_BUS_BITS_VT_KERNELS_1_6_V_DATA 8
#define XSEPIMAGEFILTER_CONTROL_BUS_ADDR_VT_KERNELS_2_0_V_DATA 0x138
#define XSEPIMAGEFILTER_CONTROL_BUS_BITS_VT_KERNELS_2_0_V_DATA 8
#define XSEPIMAGEFILTER_CONTROL_BUS_ADDR_VT_KERNELS_2_1_V_DATA 0x140
#define XSEPIMAGEFILTER_CONTROL_BUS_BITS_VT_KERNELS_2_1_V_DATA 8
#define XSEPIMAGEFILTER_CONTROL_BUS_ADDR_VT_KERNELS_2_2_V_DATA 0x148
#define XSEPIMAGEFILTER_CONTROL_BUS_BITS_VT_KERNELS_2_2_V_DATA 8
#define XSEPIMAGEFILTER_CONTROL_BUS_ADDR_VT_KERNELS_2_3_V_DATA 0x150
#define XSEPIMAGEFILTER_CONTROL_BUS_BITS_VT_KERNELS_2_3_V_DATA 8
#define XSEPIMAGEFILTER_CONTROL_BUS_ADDR_VT_KERNELS_2_4_V_DATA 0x158
#define XSEPIMAGEFILTER_CONTROL_BUS_BITS_VT_KERNELS_2_4_V_DATA 8
#define XSEPIMAGEFILTER_CONTROL_BUS_ADDR_VT_KERNELS_2_5_V_DATA 0x160
#define XSEPIMAGEFILTER_CONTROL_BUS_BITS_VT_KERNELS_2_5_V_DATA 8
#define XSEPIMAGEFILTER_CONTROL_BUS_ADDR_VT_KERNELS_2_6_V_DATA 0x168
#define XSEPIMAGEFILTER_CONTROL_BUS_BITS_VT_KERNELS_2_6_V_DATA 8
#define XSEPIMAGEFILTER_CONTROL_BUS_ADDR_CONFIG_V_DATA         0x170
#define XSEPIMAGEFILTER_CONTROL_BUS_BITS_CONFIG_V_DATA         8
#define XSEPIMAGEFILTER_CONTROL_BUS_ADDR_DIVISOR_0_V_DATA      0x178
#define XSEPIMAGEFILTER_CONTROL_BUS_BITS_DIVISOR_0_V_DATA      20
#define XSEPIMAGEFILTER_CONTROL_BUS_ADDR_DIVISOR_1_V_DATA      0x180
#define XSEPIMAGEFILTER_CONTROL_BUS_BITS_DIVISOR_1_V_DATA      20
#define XSEPIMAGEFILTER_CONTROL_BUS_ADDR_DIVISOR_2_V_DATA      0x188
#define XSEPIMAGEFILTER_CONTROL_BUS_BITS_DIVISOR_2_V_DATA      20

